version: '3'
services:
  speedtest:
    container_name: docker-speedtest-analyser
    build: .
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./data:/var/www/html/data
    ports:
      - 8080:80
      - 4343:443
    environment:
      - CRONJOB_ITERATION=10
